name: Python package
on: [push]

jobs:
  prepare-sqlite:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - if: steps.sqlite-amalgamation.outputs.cache-hit != 'true'
      run: |
        cd sqlite/
        LIBS="-lm" ./configure --disable-tcl --enable-tempstore=always
        make sqlite3.c
    - uses: actions/upload-artifact@v3
      with:
        name: sqlite-amalgamation
        path: |
          sqlite/sqlite3.c
          sqlite/sqlite3.h

  tests:
    needs: [prepare-sqlite]

    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/download-artifact@v3
      with:
        name: sqlite-amalgamation
        path: ./
    - name: Build module
      run: |
        python setup.py build_ext -i
    - name: Run tests
      run: |
        python -m test

  build-wheels:
    needs: [prepare-sqlite, tests]

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - uses: actions/download-artifact@v3
      with:
        name: sqlite-amalgamation
        path: ./
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel cibuildwheel
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_SKIP: pp*
    - uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: ./wheelhouse/*.whl

  build-sdist:
    needs: [prepare-sqlite, tests]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - uses: actions/download-artifact@v3
      with:
        name: sqlite-amalgamation
        path: ./
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel
    - name: Build sdist
      run: |
        python setup.py sdist
    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz

  upload-pypi:
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
